name: Angular Github Pages Deployment
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Config GitHub Actions Bot
         run: |
           git config user.name 'Cameron Brown'
           git config user.email 'cameronjoebrown@gmail.com'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build --configuration production
      - name: Deploy to GitHub Pages
        run: yarn deploy
